In [1]:
import numpy as np

1. 1.	Create a 1D array containing numbers from 0 to 9.

In [2]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


2.	Create a 3×3 array filled with all True values.

In [3]:
arr2 = np.ones((3,3))

print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.	Create a 5×5 identity matrix using NumPy.

In [4]:
#arr3 = np.identity(5)

#print(arr3)

arr3 = np.zeros((5,5))
for i in range(5):
  arr3[i][i] = 1

print(arr3)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


4.	Create a 3×3 matrix with random integers between 1 and 10.

In [5]:
arr4 = np.random.randint(1, 10, 9).reshape(3, 3)

print(arr4)

[[8 6 1]
 [8 3 3]
 [7 7 4]]


5.	Create an array of 10 zeros and 10 ones, then concatenate them.

In [6]:
arrZeros = np.zeros(10)
arrOnes = np.ones(10)

print(np.concatenate([arrZeros, arrOnes]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


6.	Create an array of shape (3, 4) and print its shape, size, and data type.

In [7]:
arr5 = np.arange(1, 13).reshape(3, 4)

print(arr5.shape)
print(arr5.size)
print(arr5.dtype)

(3, 4)
12
int64


7.	Create a 1D array with elements [10, 20, 30, 40, 50]. Print the first element, last element, and a slice of the middle three.

In [8]:
arr6 = np.arange(10, 51, 10)

print(arr6[0])
print(arr6[-1])
print(arr6[1:-1])

10
50
[20 30 40]


8.	Create an array of floats from 0 to 1 with 10 evenly spaced values.

In [9]:
arr7 = np.linspace(0, 1, 10)

print(arr7)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


9.	Generate a 2×3 array of random numbers and print its mean, min, and max.

In [10]:
arr8 = np.random.randint(1, 10, 6).reshape(2, 3)

print(np.mean(arr8))
print(np.min(arr8))
print(np.max(arr8))

4.666666666666667
1
9


10.	Create an array of 15 numbers from 10 to 100 with equal spacing.

In [11]:
arr9 = np.linspace(10, 100, 15)

print(arr9)

[ 10.          16.42857143  22.85714286  29.28571429  35.71428571
  42.14285714  48.57142857  55.          61.42857143  67.85714286
  74.28571429  80.71428571  87.14285714  93.57142857 100.        ]


11.	Create a = np.arange(20) and extract elements from index 5 to 10.

In [12]:
a =np.arange(20)

print(a[5])
print(a[6])
print(a[7])
print(a[8])
print(a[9])
print(a[10])

5
6
7
8
9
10


12.	From the array b = np.arange(1, 26).reshape(5, 5), extract: the first row, last column, and a 2×2 subarray from the top-left corner.

In [13]:
b = np.arange(1, 26).reshape(5, 5)

print(b[0, :])
print(b[:, -1])
print(b[:2, :2])

[1 2 3 4 5]
[ 5 10 15 20 25]
[[1 2]
 [6 7]]


13.	Replace all even numbers in an array of 0–10 with -1.


In [14]:
arr9 = np.arange(1, 11)

#print(arr9[arr9 % 2 == 0])
#arr9 = np.where(arr9 % 2 == 0, -1, arr9)
arr9[arr9 % 2 == 0] = -1

print(arr9)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


14.	Create an array of numbers 1–9 and reverse it.

In [15]:
arr10 = np.arange(1, 10)

print(arr10[::-1])

[9 8 7 6 5 4 3 2 1]


15.	Extract all odd numbers from an array np.arange(1, 20).

In [16]:
arr11 = np.arange(1, 20)

print(arr11[arr11 % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


16.	Create two arrays a and b each with 5 random integers (1–10). Perform elementwise addition, subtraction, multiplication, and division.

In [17]:
a = np.random.randint(1, 11, 10)
b = np.random.randint(1, 11, 10)

print("a: ", a)
print("b: ", b)

print("Addition: ", a + b)
print("Substraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a // b)

a:  [4 3 4 5 8 2 9 4 6 7]
b:  [ 4 10  6  8  4  7  9  5  9  2]
Addition:  [ 8 13 10 13 12  9 18  9 15  9]
Substraction:  [ 0 -7 -2 -3  4 -5  0 -1 -3  5]
Multiplication:  [16 30 24 40 32 14 81 20 54 14]
Division:  [1 0 0 0 2 0 1 0 0 3]


17.	Create a 3×3 array with values from 1 to 9 and compute the sum of all elements.

In [18]:
arr12 = np.arange(1, 10).reshape(3, 3)

print("Sum of all: ", np.sum(arr))

Sum of all:  45


18.	Compute the row-wise and column-wise sums of a 2D array.

In [19]:
arr13 = np.arange(1,10).reshape(3,3)
print(arr13)
print("Row: ", arr13.sum(axis = 0))
print("Column: ", arr13.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row:  [12 15 18]
Column:  [ 6 15 24]


19.	Create an array [1, 2, 3, 4, 5] and square every element.

In [20]:
numList = [1, 2, 3, 4, 5]
arr14 = np.array(numList)

print(arr14 ** 2)

[ 1  4  9 16 25]


20.	For the array [1, 2, 3, 4, 5], compute the mean, standard deviation, and variance.

In [21]:
arr15 = np.arange(1, 6)

print(np.mean(arr15))
print(np.std(arr15))
print(np.var(arr15))

3.0
1.4142135623730951
2.0


21.	Create an array of 12 elements and reshape it into a 3×4 matrix.

In [22]:
arr16 = np.arange(1, 13).reshape(3, 4)

print(arr16)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


22.	Create two 2×2 arrays and vertically stack them.

In [23]:
one = np.random.randint(1, 10, 4).reshape(2, 2)
two = np.random.randint(1, 10, 4).reshape(2, 2)

print(np.vstack([one, two]))

[[7 2]
 [6 6]
 [4 8]
 [3 2]]


23.	Create two 2×2 arrays and horizontally stack them.

In [24]:
three = np.random.randint(1, 10, 4).reshape(2, 2)
four = np.random.randint(1, 10, 4).reshape(2, 2)

print(np.hstack([three, four]))

[[7 7 5 5]
 [8 4 4 4]]


24.	Flatten a 3×3 matrix into a 1D array.

In [25]:
arr17 = np.random.randint(1, 9, 9).reshape(3, 3)
print(arr17)
print("Flattened: \n", arr17.ravel())

[[3 7 2]
 [7 2 8]
 [7 4 4]]
Flattened: 
 [3 7 2 7 2 8 7 4 4]


25.	Generate a 4×4 matrix of random integers between 10 and 99. Find: the maximum value, the minimum value, and the index of the maximum value.

In [26]:
arr18 = np.random.randint(10, 99, 16).reshape(4, 4)

print(arr18)
print("max: ", np.max(arr18))
print("min: ", np.min(arr18))
print("Index: ", np.argmax(arr18))

[[23 26 93 60]
 [10 35 39 12]
 [55 77 87 22]
 [69 41 16 14]]
max:  93
min:  10
Index:  2


--------- Practice ----------------

In [27]:
p1 = np.arange(1,10)

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[1:, 1:])

[[5 6]
 [8 9]]


In [28]:
p2 = np.array([1,2,3,4,2,3,2,4,2])

#print(np.unique(p2))

values, counts = np.unique(p2, return_counts=True)
print("The unique values are: ", values)
print("The frequency of the values in order: ", counts)

The unique values are:  [1 2 3 4]
The frequency of the values in order:  [1 4 2 2]
